# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: Default
 demands: Unity_2019.3.10f1

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  lfs: true

- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Android'
    unityEditorsPathMode: 'specify'
    customUnityEditorsPath: 'C:\Program Files'
    unityProjectPath: 'CyclopsVR'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'CyclopsVR_Android'

#- task: UnityTestTask@1
#  inputs:
#    unityEditorsPathMode: 'specify'
#    customUnityEditorsPath: 'C:\Program Files'
#    unityProjectPath: 'CyclopsVR'
    
- task: ArchiveFiles@1
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/CyclopsVR_Android'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/CyclopsVR_Android_$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: CopyFiles@1
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '*.zip'
    TargetFolder: 'C:\Repos\official github\Cyclops-VR\Builds'
    OverWrite: true